### ISSUE TITLE
Research about the creation of a `ProverProof` using the KZG backend in Kimchi

### ISSUE THREAD

**Issue by xqft** [lambdaclass/mina_bridge#98]
Recently I tried to generate this structure, which holds the KZG `PairingProof`, commitments and evaluations of some polys that are needed for running the partial verification both in Kimchi and in the Solidity verifier. I ran into multiple problems and in the end got blocked with this error message:

```bash
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Prover("rest of division by vanishing polynomial")', src/main.rs:214:6
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
if we go to the [source of this error](https://github.com/lambdaclass/proof-systems/blob/wasm_kzg_prover/kimchi/src/prover.rs#L860) we determine that the program failed to create the `ProverProof` because the final aggregated polynomial `f` is not divisible by the vanishing polynomial, so the quotient poly can't be calculated.

Before this error, I had a problem with the circuit's domain: currently the KZG prover (based on various Kimchi use-case tests) creates a separate `EvaluationDomain` with a size bigger than the number of gates of the circuit, by adding up a `ZK_ROWS = 3` constant. It then uses this for computing the SRS (and so the lagrange bases). If we try to create the `ProverProof` with this, then it fails because the size of this evaluation domain is 64 while our circuit has 32 gates (64 is the next power of two bigger than 32 + 3 = `domain_size + ZK_ROWS`, and powers of two are used because the domain needs to be FFT friendly) and so it can't find lagrange bases corresponding to the 32-sized domain because the SRS was created with the 64-sized one. So I changed this to use the actual constraint system's domain (and ignoring the 64 sized one) and it worked, partially, because it removed this error, but now I arrived to the one that's shown above. **Maybe chossing to discard this domain is causing this error**. A possible solution may be making Kimchi use the 64 sized domain.

**Comment by pablodeymo** [comment]
I think this is obsolete
